language: node_js
node_js:
  - 10

install:
 - npm install --save

script:
 - npm run build:all
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name ENV(GITHUB_USERNAME)
  - git config --local user.email ENV(GITHUB_USER_EMAIL)
  - export TRAVIS_TAG=$(node -pe "require('./package.json').version")
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: ENV(GITHUB_TOKEN)
  file: "./build/*"
  skip_cleanup: true
  on:
    tags: true