# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install
      - node/install-packages:
          override-ci-command: npm install --save
          with-cache: false
      - run: 
          command: npm run build:latest
      - persist_to_workspace:
          root: ~/
          paths:
            - project/build
  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ~/project/build
      - node/install:
          install-npm: false 
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(node -pe "require('./package.json').version")
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  release:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build

